### ISSUE TITLE
shulkerBoxItemsDropContents

### ISSUE THREAD

**Issue by rabandola** [JohanVonElectrum/Johan-Carpet#21]
la implementacion de 1.17 de romper shulkers con lava en 1.16

**Comment by JohanVonElectrum** [comment]
Ya está en 1.16: https://github.com/JohanVonElectrum/Johan-Carpet/commit/ef343b9cc66810107a04df4ba1fa86eebbba4648
Luego lo pongo en 1.17 y 1.18 cuando haga update de todo.

**Comment by JohanVonElectrum** [comment]
Listo: https://github.com/JohanVonElectrum/Johan-Carpet/commit/ef343b9cc66810107a04df4ba1fa86eebbba4648
Hoy o mañana estará en la release.
