### ISSUE TITLE
Incompatibility With Plusls Carpet Addition

### ISSUE THREAD

**Issue by ZuccySuccy** [JohanVonElectrum/Johan-Carpet#22]
Game fails to load when [Plusls Carpet](https://github.com/plusls/plusls-carpet-addition) is in the mod folder. This is with the most recent versions of both mods along with carpet and the FAPI (which plusls is dependent on)

[Here's the latest log](https://github.com/JohanVonElectrum/Johan-Carpet/files/7699939/latest.log)

I'm not sure which mod is the actual issue, so I'm essentially making the same report on both github pages

**Comment by JohanVonElectrum** [comment]
plusls fixed: https://github.com/plusls/plusls-carpet-addition/issues/14
