### ISSUE TITLE
Actualizar a la version 1.18.2

### ISSUE THREAD

**Issue by Naxx19** [JohanVonElectrum/Johan-Carpet#59]
hola, por favor siga actualizando el johan carpet

**Comment by IPalmorX** [comment]
Hello friend, this is a stable version that was able to work for 1.18.2

https://github.com/IPalmorX/Johan-Carpet-1.18.2/releases/download/1.18.2/johan-carpet-1.18.2-2021.12.18.jar

**Comment by JohanVonElectrum** [comment]
Thanks for the response. I'll close this issue now.
