### ISSUE TITLE
Notificación de nueva versión disponible.

### ISSUE THREAD

**Issue by JorgeBalbontin** [JohanVonElectrum/Johan-Carpet#6]
Al cargar el mundo  sale que hay nueva versión, siendo esta la última.

**Comment by JohanVonElectrum** [comment]
Debería estar arreglado con este parche: https://github.com/JohanVonElectrum/Johan-Carpet/commit/8a689820d455341122e6cc3ffef184f3c461f885

En la próxima versión estará disponible.
