### ISSUE TITLE
Romper bedrock como en la 1.7.8/1.7.9/1.7.10

### ISSUE THREAD

**Issue by ghost** [JohanVonElectrum/Johan-Carpet#68]
En las versiones 1.7.8,1.7.9 y 1.7.10 hay un bug que te permite romper bedrock colocando un escalón justo en frente del bloque de bedrock y luego poniendo una calavera de esqueleto wither encima del escalón.

Dejo este vídeo para mayor claridad: https://youtu.be/8QZ_n9Nd2nM (Minuto 2:29)

**Comment by JohanVonElectrum** [comment]
Movido a Koralix-Studios/one-for-all#2
