### ISSUE TITLE
Actualizar a 1.20.1

### ISSUE THREAD

**Issue by Naxx19** [JohanVonElectrum/Johan-Carpet#70]
Holaa, por favor si no es molestia, podria actualizar el mod a esa version.

**Comment by JohanVonElectrum** [comment]
Estamos migrando el JohanCarpet a un mod nuevo independiente de Carpet que tiene un mejor soporte para más funcionalidades. Puedes encontrarlo aquí y ver nuestro progreso: https://github.com/Koralix-Studios/one-for-all
closes #70, closes #69, closes #65, closes #64, closes #63
