### ISSUE TITLE
Revive for 1.21?

### ISSUE THREAD

**Issue by sternschnaube** [JohanVonElectrum/Johan-Carpet#72]

**Comment by JohanVonElectrum** [comment]
We are currently migrating this project to a new repository. This new mod will be independent of Carpet and will have a more modern approach to let us implement more complex features. You can track our progress and subscribe for updates on our new repository: https://github.com/Koralix-Studios/one-for-all
Thanks for your support!

**Comment by sternschnaube** [comment]
Awesome news, thanks!
